service: trivia-game-lobby
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handlers/handler.hello
    events:
      - http:
          path: hello-world
          method: get
          cors: true