service: user-profile-management
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:*'
        - 'sqs:*'
        - 'dynamodb:*' 
      Resource: '*'
  role: arn:aws:iam::694195453932:role/LabRole
  environment:
    USER_TABLE: ${self:service}-${self:provider.stage}-users

functions:
  add-user:
    handler: handlers/add-user.handler
    description: POST /user
    events:
      - http:
          path: user
          method: post
          cors:
            origin: '*'

resources:
  Resources:
    UserTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.environment.USER_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1