service: user-profile-management
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:*'
        - 'sqs:*'
        - 'dynamodb:*' 
      Resource: '*'
  role: arn:aws:iam::694195453932:role/LabRole
  environment:
    USER_TABLE: ${self:service}-${self:provider.stage}-users
    USER_QUS_ANS_TABLE: ${self:service}-${self:provider.stage}-users-two-factor-question-answer

functions:
  add-user:
    handler: handlers/add-user.handler
    description: POST /user
    events:
      - http:
          path: user
          method: post
          cors:
            origin: '*'
  add-user-que-ans:
    handler: handlers/add-user-answers.handler
    description: POST /user-answers
    events:
      - http:
          path: user-answers
          method: post
          cors:
            origin: '*'
  get-user-que-ans:
    handler: handlers/get-user-answers.handler
    description: Get /user-answers
    events:
      - http:
          path: user-answers
          method: get
          request:
            parameters:
              querystrings:
                email: true
                user_id: true
          cors:
            origin: '*'
  validate-user-que-ans:
    handler: handlers/validate-auth-answers.handler
    description: validate /user-answers
    events:
      - http:
          path: validate-auth-answers
          method: post
          cors:
            origin: '*'

resources:
  Resources:
    UserTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.USER_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    userTwoFactorQuestionAnswers:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.USER_QUS_ANS_TABLE}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1