
service: in-game-experience
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:*'
        - 'sqs:*'
      Resource: '*'
  role: arn:aws:iam::<account-id>:role/LabRole

functions:
  hello:
    handler: handlers/index.hello
    events:
      - http:
          path: hello-world
          method: get
          cors: true