
service: in-game-experience
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: index.hello
    events:
      - http:
          path: hello-world
          method: get
          cors: true