
service: in-game-experience
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:*'
        - 'sqs:*'
        - 'dynamodb:*' 
      Resource: '*'
  role: arn:aws:iam::694195453932:role/LabRole

functions:
  add-user:
    handler: handlers/get-questions.handler
    description: GET /game-questions
    events:
      - http:
          path: game-questions
          method: get
          cors:
            origin: '*'
          request:
            parameters:
              querystrings:
                game_id: true
